### ISSUE TITLE
Error to run keras_trade.py

### ISSUE THREAD

**Issue by snowsky** [ryogrid/fx_systrade#3]
Hi there,

When I run the script, I've got this error. Is it the API deprecated? Thanks.

`keras_trade.py:346: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(50, activation="relu", kernel_initializer="uniform", input_shape=(17,))`
  model.add(Dense(neuro_num,input_shape=(dims,), init='uniform', activation="relu"))
Traceback (most recent call last):
  File "keras_trade.py", line 347, in <module>
    model.add(BatchNormalization((neuro_num,),input_shape=(dims,)))
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 30, in wrapper
    args, kwargs, converted = preprocessor(args, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 440, in batchnorm_args_preprocessor
    raise TypeError('The `BatchNormalization` layer '
TypeError: The `BatchNormalization` layer does not accept positional arguments. Use keyword arguments instead.`

**Comment by 99thpixel** [comment]
I'm getting the same error.
